Traceback (most recent call last):
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\zschende\Miniconda3\envs\atbd\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
l2_grid = 'testcard_ease2_1km'
area_def = pr.load_area('../algorithm/testcard_adef.yaml',l2_grid)

cart_crs = area_def.to_cartopy_crs()
# extent = cart_crs.bounds
trg_lon, trg_lat = area_def.get_lonlats()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[3], line 2[0m
[0;32m      1[0m l2_grid [38;5;241m=[39m [38;5;124m'[39m[38;5;124mtestcard_ease2_1km[39m[38;5;124m'[39m
[1;32m----> 2[0m area_def [38;5;241m=[39m [43mpr[49m[38;5;241;43m.[39;49m[43mload_area[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../algorithm/testcard_adef.yaml[39;49m[38;5;124;43m'[39;49m[43m,[49m[43ml2_grid[49m[43m)[49m
[0;32m      4[0m cart_crs [38;5;241m=[39m area_def[38;5;241m.[39mto_cartopy_crs()
[0;32m      5[0m [38;5;66;03m# extent = cart_crs.bounds[39;00m

File [1;32m~\Miniconda3\envs\atbd\Lib\site-packages\pyresample\area_config.py:91[0m, in [0;36mload_area[1;34m(area_file_name, *regions)[0m
[0;32m     66[0m [38;5;28;01mdef[39;00m [38;5;21mload_area[39m(area_file_name, [38;5;241m*[39mregions):
[0;32m     67[0m [38;5;250m    [39m[38;5;124;03m"""Load area(s) from area file.[39;00m
[0;32m     68[0m 
[0;32m     69[0m [38;5;124;03m    Parameters[39;00m
[1;32m   (...)[0m
[0;32m     89[0m [38;5;124;03m        If a specified area name is not found[39;00m
[0;32m     90[0m [38;5;124;03m    """[39;00m
[1;32m---> 91[0m     area_list [38;5;241m=[39m [43mparse_area_file[49m[43m([49m[43marea_file_name[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43mregions[49m[43m)[49m
[0;32m     92[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m(area_list) [38;5;241m==[39m [38;5;241m1[39m:
[0;32m     93[0m         [38;5;28;01mreturn[39;00m area_list[[38;5;241m0[39m]

File [1;32m~\Miniconda3\envs\atbd\Lib\site-packages\pyresample\area_config.py:147[0m, in [0;36mparse_area_file[1;34m(area_file_name, *regions)[0m
[0;32m    126[0m [38;5;250m[39m[38;5;124;03m"""Parse area information from area file.[39;00m
[0;32m    127[0m 
[0;32m    128[0m [38;5;124;03mParameters[39;00m
[1;32m   (...)[0m
[0;32m    144[0m [38;5;124;03m    If a specified area is not found[39;00m
[0;32m    145[0m [38;5;124;03m"""[39;00m
[0;32m    146[0m [38;5;28;01mtry[39;00m:
[1;32m--> 147[0m     [38;5;28;01mreturn[39;00m [43m_parse_yaml_area_file[49m[43m([49m[43marea_file_name[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43mregions[49m[43m)[49m
[0;32m    148[0m [38;5;28;01mexcept[39;00m (yaml[38;5;241m.[39mscanner[38;5;241m.[39mScannerError, yaml[38;5;241m.[39mparser[38;5;241m.[39mParserError):
[0;32m    149[0m     [38;5;28;01mreturn[39;00m _parse_legacy_area_file(area_file_name, [38;5;241m*[39mregions)

File [1;32m~\Miniconda3\envs\atbd\Lib\site-packages\pyresample\area_config.py:195[0m, in [0;36m_parse_yaml_area_file[1;34m(area_file_name, *regions)[0m
[0;32m    183[0m [38;5;28;01mdef[39;00m [38;5;21m_parse_yaml_area_file[39m(area_file_name, [38;5;241m*[39mregions):
[0;32m    184[0m [38;5;250m    [39m[38;5;124;03m"""Parse area information from a yaml area file.[39;00m
[0;32m    185[0m 
[0;32m    186[0m [38;5;124;03m    Args:[39;00m
[1;32m   (...)[0m
[0;32m    193[0m [38;5;124;03m    that.[39;00m
[0;32m    194[0m [38;5;124;03m    """[39;00m
[1;32m--> 195[0m     area_dict [38;5;241m=[39m [43m_read_yaml_area_file_content[49m[43m([49m[43marea_file_name[49m[43m)[49m
[0;32m    196[0m     area_list [38;5;241m=[39m regions [38;5;129;01mor[39;00m area_dict[38;5;241m.[39mkeys()
[0;32m    197[0m     res [38;5;241m=[39m []

File [1;32m~\Miniconda3\envs\atbd\Lib\site-packages\pyresample\area_config.py:176[0m, in [0;36m_read_yaml_area_file_content[1;34m(area_file_name)[0m
[0;32m    174[0m         tmp_dict [38;5;241m=[39m yaml[38;5;241m.[39msafe_load(area_file_obj)
[0;32m    175[0m     [38;5;28;01melse[39;00m:
[1;32m--> 176[0m         [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43marea_file_obj[49m[43m)[49m [38;5;28;01mas[39;00m area_file_obj:
[0;32m    177[0m             tmp_dict [38;5;241m=[39m yaml[38;5;241m.[39msafe_load(area_file_obj)
[0;32m    178[0m area_dict [38;5;241m=[39m recursive_dict_update(area_dict, tmp_dict)

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../algorithm/testcard_adef.yaml'
FileNotFoundError: [Errno 2] No such file or directory: '../algorithm/testcard_adef.yaml'

